# 职准星 - 核心模块统一导出
#
# 导出内容：
#   config.*       — 全部配置常量（LLM超时、限流、会话TTL、文件限制、缓存、向量库路径、自动清理）
#   llm_client     — 全局 LLM 客户端单例（LLMClient 实例）
#   LLMError       — LLM 调用异常基类
#   token_stats    — 全局 Token 统计单例
#   全部 prompt 模板 — CHAT / ASSESSMENT / REASON / GAP / REPORT / RULE_JUDGE 六大模块

from .config import (
    # LLM 配置
    DEEPSEEK_API_KEY, DEEPSEEK_BASE_URL, LLM_MODEL,
    LLM_TIMEOUT, LLM_MAX_RETRIES,
    LLM_TEMPERATURE_CHAT, LLM_TEMPERATURE_ANALYSIS,
    LLM_TEMPERATURE_REASONING, LLM_TEMPERATURE_FORMAT,
    LLM_TEMPERATURE_OPTIMIZE, LLM_TEMPERATURE_COUNTERATTACK,
    LLM_DISABLE_DEEP_THINK,
    LLM_MAX_TOKENS_CHAT, LLM_MAX_TOKENS_ANALYSIS,
    LLM_MAX_TOKENS_REASONING, LLM_MAX_TOKENS_DIAGNOSIS,
    LLM_MAX_TOKENS_OPTIMIZE, LLM_MAX_TOKENS_COUNTERATTACK, LLM_MAX_TOKENS_FORMAT,
    # 向量库
    CHROMA_DB_PATH, KB_CHUNK_SIZE, KB_CHUNK_OVERLAP,
    KB_MIN_SCORE, KB_JD_MIN_SCORE, KB_CONTEXT_MAX_LENGTH,
    # 限流
    RATE_LIMIT_PER_MINUTE, MAX_CONCURRENT_SESSIONS, SESSION_LLM_CALLS_PER_30S,
    # 会话
    MAX_SESSION_HOURS, SESSION_CLEANUP_INTERVAL_MINUTES,
    CHAT_HISTORY_MAX_ROUNDS, CHAT_HISTORY_RECENT_N,
    # 文件
    MAX_FILE_SIZE, MAX_INPUT_LENGTH, MAX_MESSAGE_LENGTH,
    MAX_RESUME_LENGTH, MAX_JD_LENGTH,
    # 缓存
    REPORT_CACHE_MINUTES,
    # 清理
    ENABLE_AUTO_CLEANUP, CLEANUP_FILE_MAX_AGE_HOURS, CLEANUP_INTERVAL_HOURS,
    # CORS
    CORS_ORIGINS,
    # 服务
    HOST, PORT,
    # 路径
    UPLOAD_DIR, REPORT_DIR, KNOWLEDGE_DIR, JDS_DIR,
    JUDGMENT_RULES_FILE, HOLLAND_GUIDE_FILE,
    DATABASE_URL,
    # 日志
    LOG_LEVEL, LOG_FORMAT,
    # 安全
    SENSITIVE_PATTERNS, HARMFUL_PATTERNS,
    # 函数
    init_dirs, validate_config,
)

from .llm import (
    llm_client,
    LLMClient,
    LLMError,
    LLMRateLimitError,
    LLMAuthError,
    LLMTimeoutError,
    token_stats,
    TokenStats,
)

from .prompts import (
    # CHAT
    CHAT_SYSTEM_PROMPT,
    CHAT_USER_PROMPT_TEMPLATE,
    CHAT_HISTORY_CONTEXT_TEMPLATE,
    CHAT_INTRO_DELIVERED_HINT,
    # ASSESSMENT
    ANALYZE_Q1_SYSTEM, ANALYZE_Q1_USER_TEMPLATE,
    ANALYZE_Q2_SYSTEM, ANALYZE_Q2_USER_TEMPLATE,
    ANALYZE_Q3_SYSTEM, ANALYZE_Q3_USER_TEMPLATE,
    ANALYZE_Q4_SYSTEM, ANALYZE_Q4_USER_TEMPLATE,
    ANALYZE_Q5_SYSTEM, ANALYZE_Q5_USER_TEMPLATE,
    ANALYZE_Q6_SYSTEM, ANALYZE_Q6_USER_TEMPLATE,
    ASSESSMENT_QUESTIONS,
    # REASON
    REASONING_SYSTEM_PROMPT,
    REASONING_USER_PROMPT_TEMPLATE,
    FORMAT_RECOMMEND_SYSTEM,
    FORMAT_RECOMMEND_USER_TEMPLATE,
    # GAP
    NODE1_SYSTEM_PROMPT, NODE1_USER_PROMPT_TEMPLATE,
    NODE2_SYSTEM_PROMPT, NODE2_USER_PROMPT_TEMPLATE,
    NODE4_SYSTEM_PROMPT, NODE4_USER_PROMPT_TEMPLATE,
    NODE5_SYSTEM_PROMPT, NODE5_USER_PROMPT_TEMPLATE,
    NODE6_SYSTEM_PROMPT, NODE6_USER_PROMPT_TEMPLATE,
    # REPORT
    REPORT_HEADER_TEMPLATE,
    REPORT_SUMMARY_TEMPLATE,
    # RULE
    FALLBACK_JUDGMENT_RULES,
)

__all__ = [
    # config 常量
    'DEEPSEEK_API_KEY', 'DEEPSEEK_BASE_URL', 'LLM_MODEL',
    'LLM_TIMEOUT', 'LLM_MAX_RETRIES',
    'LLM_TEMPERATURE_CHAT', 'LLM_TEMPERATURE_ANALYSIS',
    'LLM_TEMPERATURE_REASONING', 'LLM_TEMPERATURE_FORMAT',
    'LLM_TEMPERATURE_OPTIMIZE', 'LLM_TEMPERATURE_COUNTERATTACK',
    'CHROMA_DB_PATH', 'RATE_LIMIT_PER_MINUTE', 'MAX_CONCURRENT_SESSIONS',
    'MAX_SESSION_HOURS', 'MAX_FILE_SIZE', 'REPORT_CACHE_MINUTES',
    'ENABLE_AUTO_CLEANUP', 'CORS_ORIGINS', 'HOST', 'PORT',
    'UPLOAD_DIR', 'REPORT_DIR', 'LOG_LEVEL',
    'init_dirs', 'validate_config',
    # llm
    'llm_client', 'LLMClient', 'LLMError', 'token_stats',
    # prompts — 分组名导出（不逐个导出全部避免命名空间膨胀）
]
